In [149]:
# Importing the needed libraries 
import numpy as np
import pandas as pd

In [162]:
# Reading of the dataset
df = pd.read_csv('heart_disease.csv')
houseprice = pd.DataFrame(df)
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [163]:
# Showing the information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             4238 non-null   int64  
 1   age              4238 non-null   int64  
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64  
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64  
 7   prevalentHyp     4238 non-null   int64  
 8   diabetes         4238 non-null   int64  
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 529.9 KB


In [ ]:
# Showing the features in the dataset

In [208]:
df.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [164]:
# Describing the dataset
df.describe

<bound method NDFrame.describe of       male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0      

In [165]:
# Checking the missing values
df.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [ ]:
# Preprocessing the dataset

In [166]:
from sklearn.preprocessing import scale,MinMaxScaler
from sklearn.impute import SimpleImputer

In [167]:
min_max = MinMaxScaler()

imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
# Splitting dataset in dependent and independent

In [170]:
x = df.loc[:,['male','age','education','currentSmoker','cigsPerDay','BPMeds','prevalentStroke','prevalentHyp','diabetes','totChol','sysBP','diaBP','BMI','heartRate','glucose']]

y = df['TenYearCHD']

In [ ]:
# Dataset into train and test

In [171]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x, y,train_size=0.5,test_size=0.5,random_state=1) 

In [ ]:
# Fitting the train and test dataset and transforming them

In [172]:
imp.fit(train_x)
imp.fit(test_x)

xnumpy = imp.transform(train_x)
xtestnum = imp.transform(test_x)

xdf = pd.DataFrame(xnumpy)
testx = pd.DataFrame(xtestnum)

In [ ]:
# Choosing a model

In [173]:
from sklearn.linear_model import LogisticRegression

In [174]:
log = LogisticRegression(penalty='l2',C=0.01)
log.fit(xdf,train_y)

C:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.01)

In [ ]:
# Applying the model

In [175]:
log.predict(testx)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
# Accuracy Checking

In [176]:
log.score(testx,test_y)

0.8607833883907503

In [177]:
x_train_minMax = min_max.fit_transform(xnumpy)
x_test_minMax = min_max.fit_transform(xtestnum)

In [178]:
log1 =  LogisticRegression(penalty='l2',C=0.2)
log1.fit(x_train_minMax,train_y)

LogisticRegression(C=0.2)

In [179]:
log1.predict(x_test_minMax)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
# Accuracy Checking

In [180]:
log.score(x_test_minMax,test_y)

0.6998584237848041

In [181]:
x_train_scale = scale(xnumpy)
x_test_scale = scale(xtestnum)

In [182]:
log2 = LogisticRegression(penalty='l2',C=.01)
log2.fit(x_train_scale,train_y)

LogisticRegression(C=0.01)

In [183]:
log2.predict(x_test_scale)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
# Accuracy Checking

In [184]:
log2.score(x_test_scale,test_y)

0.8617272298253893

In [185]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
Itmp = IterativeImputer(max_iter=10,random_state=0)

In [186]:
Itmp.fit(train_x)
Itmp.fit(test_x)

x_train_std = Itmp.transform(train_x)
xtest_std = Itmp.transform(test_x)


x_train_std_pd = pd.DataFrame(x_train_std)
xtest_std_pd = pd.DataFrame(xtest_std)

In [187]:
log3 = LogisticRegression(penalty='l2',C=.01)
log3.fit(x_train_std,train_y)

C:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.01)

In [188]:
log3.predict(xtest_std_pd)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
# Accuracy Checking

In [189]:
log3.score(xtest_std_pd,test_y)

0.8617272298253893

In [ ]:
# Choosing another model

In [190]:
from sklearn.neighbors import KNeighborsClassifier

Knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
#Fitting the model and transforming it

In [191]:
imp.fit(train_x)
imp.fit(test_x)

x_array = imp.transform(train_x)
xtest_array = imp.transform(test_x)


Xframe = pd.DataFrame(x_array)
testx = pd.DataFrame(xtest_array)

In [192]:
Knn.fit(Xframe,train_y)

KNeighborsClassifier()

In [ ]:
# Applying the model

In [193]:
Knn.predict(testx)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
#Checking accuracy of the model

In [194]:
Knn.score(testx,test_y)

0.8419065596979708

In [195]:
x_train_minMax = min_max.fit_transform(x_array)
x_test_minMax = min_max.fit_transform(xtest_array)

In [196]:
Knn1 = KNeighborsClassifier(n_neighbors=5)
Knn1.fit(x_train_minMax,train_y)

KNeighborsClassifier()

In [197]:
Knn1.predict(x_test_minMax)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
#Checking accuracy of the model

In [198]:
Knn1.score(x_test_minMax,test_y)

0.8386031146767343

In [199]:
x_train_scale = scale(x_array)
x_test_scale = scale(xtest_array)

In [200]:
Knn2 = KNeighborsClassifier(n_neighbors=5)
Knn2.fit(x_train_scale,train_y)

KNeighborsClassifier()

In [201]:
Knn2.predict(x_test_scale)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
#Checking accuracy of the model

In [202]:
Knn2.score(x_test_minMax,test_y)

0.854648419065597

In [203]:
Itmp.fit(train_x)
Itmp.fit(test_x)

x_train_std = Itmp.transform(train_x)
xtest_std = Itmp.transform(test_x)


x_train_std_pd = pd.DataFrame(x_train_std)
xtest_std_pd = pd.DataFrame(xtest_std)

In [204]:
Knn3 = KNeighborsClassifier(n_neighbors=5)
Knn3.fit(x_train_std_pd,train_y)

KNeighborsClassifier()

In [205]:
Knn3.predict(xtest_std_pd)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
#Checking accuracy of the model

In [206]:
Knn3.score(testx,test_y)

0.8395469561113733

In [ ]:
## Observation

In [ ]:
After the models application, the logisticRegression model yields accuracies as 86%, and 69% and the KNN model zields 84%, 83% and 85%